config/routes.rb
Rails.application.routes.draw do
  resources :user_types
  resources :user_logs
  resources :user_accounts
  resources :skill_sets
  resources :seeker_skill_sets
  resources :seeker_profiles
  resources :job_types
  resources :job_post_skill_sets
  resources :job_post_activities
  resources :job_posts
  resources :job_locations
  resources :experience_details
  resources :education_details
  resources :company_images
  resources :companies
  resources :business_streams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/business_stream.rb
class BusinessStream < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :business_stream
end

app/models/company_image.rb
class CompanyImage < ApplicationRecord
  belongs_to :company
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/experience_detail.rb
class ExperienceDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/job_location.rb
class JobLocation < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  belongs_to :posted_by
  belongs_to :job_type
  belongs_to :company
  belongs_to :job_location
end

app/models/job_post_activity.rb
class JobPostActivity < ApplicationRecord
  belongs_to :user_account
  belongs_to :job_post
end

app/models/job_type.rb
class JobType < ApplicationRecord
end

app/models/seeker_profile.rb
class SeekerProfile < ApplicationRecord
end

app/models/seeker_skill_set.rb
class SeekerSkillSet < ApplicationRecord
  belongs_to :user_account
  belongs_to :skill_set
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :user_type
end

app/models/user_log.rb
class UserLog < ApplicationRecord
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/experience_details_controller.rb
class ExperienceDetailsController < ApplicationController
  before_action :set_experience_detail, only: [:show, :edit, :update, :destroy]

  # GET /experience_details
  # GET /experience_details.json
  def index
    @experience_details = ExperienceDetail.all
  end

  # GET /experience_details/1
  # GET /experience_details/1.json
  def show
  end

  # GET /experience_details/new
  def new
    @experience_detail = ExperienceDetail.new
  end

  # GET /experience_details/1/edit
  def edit
  end

  # POST /experience_details
  # POST /experience_details.json
  def create
    @experience_detail = ExperienceDetail.new(experience_detail_params)

    respond_to do |format|
      if @experience_detail.save
        format.html { redirect_to @experience_detail, notice: 'Experience detail was successfully created.' }
        format.json { render :show, status: :created, location: @experience_detail }
      else
        format.html { render :new }
        format.json { render json: @experience_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experience_details/1
  # PATCH/PUT /experience_details/1.json
  def update
    respond_to do |format|
      if @experience_detail.update(experience_detail_params)
        format.html { redirect_to @experience_detail, notice: 'Experience detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience_detail }
      else
        format.html { render :edit }
        format.json { render json: @experience_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experience_details/1
  # DELETE /experience_details/1.json
  def destroy
    @experience_detail.destroy
    respond_to do |format|
      format.html { redirect_to experience_details_url, notice: 'Experience detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience_detail
      @experience_detail = ExperienceDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_detail_params
      params.require(:experience_detail).permit(:user_account_id, :is_current_job, :start_date, :end_date, :job_title, :company_name, :job_location_city, :job_location_state, :job_location_country, :description)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/experience_details_helper.rb
module ExperienceDetailsHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/skill_sets_helper.rb
module SkillSetsHelper
end

app/helpers/user_logs_helper.rb
module UserLogsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/experience_details/_form.html.erb
<%= form_with(model: experience_detail, local: true) do |form| %>
  <% if experience_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience_detail.errors.count, "error") %> prohibited this experience_detail from being saved:</h2>

      <ul>
      <% experience_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_account_id %>
    <%= form.text_field :user_account_id %>
  </div>

  <div class="field">
    <%= form.label :is_current_job %>
    <%= form.text_field :is_current_job %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :job_title %>
    <%= form.text_field :job_title %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :job_location_city %>
    <%= form.text_field :job_location_city %>
  </div>

  <div class="field">
    <%= form.label :job_location_state %>
    <%= form.text_field :job_location_state %>
  </div>

  <div class="field">
    <%= form.label :job_location_country %>
    <%= form.text_field :job_location_country %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experience_details/edit.html.erb
<h1>Editing Experience Detail</h1>

<%= render 'form', experience_detail: @experience_detail %>

<%= link_to 'Show', @experience_detail %> |
<%= link_to 'Back', experience_details_path %>

app/views/experience_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experience Details</h1>

<table>
  <thead>
    <tr>
      <th>User account</th>
      <th>Is current job</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Job title</th>
      <th>Company name</th>
      <th>Job location city</th>
      <th>Job location state</th>
      <th>Job location country</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experience_details.each do |experience_detail| %>
      <tr>
        <td><%= experience_detail.user_account %></td>
        <td><%= experience_detail.is_current_job %></td>
        <td><%= experience_detail.start_date %></td>
        <td><%= experience_detail.end_date %></td>
        <td><%= experience_detail.job_title %></td>
        <td><%= experience_detail.company_name %></td>
        <td><%= experience_detail.job_location_city %></td>
        <td><%= experience_detail.job_location_state %></td>
        <td><%= experience_detail.job_location_country %></td>
        <td><%= experience_detail.description %></td>
        <td><%= link_to 'Show', experience_detail %></td>
        <td><%= link_to 'Edit', edit_experience_detail_path(experience_detail) %></td>
        <td><%= link_to 'Destroy', experience_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience Detail', new_experience_detail_path %>

app/views/experience_details/new.html.erb
<h1>New Experience Detail</h1>

<%= render 'form', experience_detail: @experience_detail %>

<%= link_to 'Back', experience_details_path %>

app/views/experience_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User account:</strong>
  <%= @experience_detail.user_account %>
</p>

<p>
  <strong>Is current job:</strong>
  <%= @experience_detail.is_current_job %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @experience_detail.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @experience_detail.end_date %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @experience_detail.job_title %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @experience_detail.company_name %>
</p>

<p>
  <strong>Job location city:</strong>
  <%= @experience_detail.job_location_city %>
</p>

<p>
  <strong>Job location state:</strong>
  <%= @experience_detail.job_location_state %>
</p>

<p>
  <strong>Job location country:</strong>
  <%= @experience_detail.job_location_country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experience_detail.description %>
</p>

<%= link_to 'Edit', edit_experience_detail_path(@experience_detail) %> |
<%= link_to 'Back', experience_details_path %>