config/routes.rb
Rails.application.routes.draw do
  resources :user_types
  resources :user_logs
  resources :user_accounts
  resources :skill_sets
  resources :seeker_skill_sets
  resources :seeker_profiles
  resources :job_types
  resources :job_post_skill_sets
  resources :job_post_activities
  resources :job_posts
  resources :job_locations
  resources :experience_details
  resources :education_details
  resources :company_images
  resources :companies
  resources :business_streams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_stream.rb
class BusinessStream < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :business_stream
end

app/models/company_image.rb
class CompanyImage < ApplicationRecord
  belongs_to :company
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/experience_detail.rb
class ExperienceDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/job_location.rb
class JobLocation < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  belongs_to :posted_by
  belongs_to :job_type
  belongs_to :company
  belongs_to :job_location
end

app/models/job_post_activity.rb
class JobPostActivity < ApplicationRecord
  belongs_to :user_account
  belongs_to :job_post
end

app/models/job_type.rb
class JobType < ApplicationRecord
end

app/models/seeker_profile.rb
class SeekerProfile < ApplicationRecord
end

app/models/seeker_skill_set.rb
class SeekerSkillSet < ApplicationRecord
  belongs_to :user_account
  belongs_to :skill_set
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :user_type
end

app/models/user_log.rb
class UserLog < ApplicationRecord
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :profile_description, :business_stream_id, :establishment_date, :company_website_url)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/skill_sets_helper.rb
module SkillSetsHelper
end

app/helpers/user_logs_helper.rb
module UserLogsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :profile_description %>
    <%= form.text_field :profile_description %>
  </div>

  <div class="field">
    <%= form.label :business_stream_id %>
    <%= form.text_field :business_stream_id %>
  </div>

  <div class="field">
    <%= form.label :establishment_date %>
    <%= form.datetime_select :establishment_date %>
  </div>

  <div class="field">
    <%= form.label :company_website_url %>
    <%= form.text_field :company_website_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Profile description</th>
      <th>Business stream</th>
      <th>Establishment date</th>
      <th>Company website url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.profile_description %></td>
        <td><%= company.business_stream %></td>
        <td><%= company.establishment_date %></td>
        <td><%= company.company_website_url %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @company.company_name %>
</p>

<p>
  <strong>Profile description:</strong>
  <%= @company.profile_description %>
</p>

<p>
  <strong>Business stream:</strong>
  <%= @company.business_stream %>
</p>

<p>
  <strong>Establishment date:</strong>
  <%= @company.establishment_date %>
</p>

<p>
  <strong>Company website url:</strong>
  <%= @company.company_website_url %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>