config/routes.rb
Rails.application.routes.draw do
  resources :user_types
  resources :user_logs
  resources :user_accounts
  resources :skill_sets
  resources :seeker_skill_sets
  resources :seeker_profiles
  resources :job_types
  resources :job_post_skill_sets
  resources :job_post_activities
  resources :job_posts
  resources :job_locations
  resources :experience_details
  resources :education_details
  resources :company_images
  resources :companies
  resources :business_streams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/business_stream.rb
class BusinessStream < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :business_stream
end

app/models/company_image.rb
class CompanyImage < ApplicationRecord
  belongs_to :company
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/experience_detail.rb
class ExperienceDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/job_location.rb
class JobLocation < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  belongs_to :posted_by
  belongs_to :job_type
  belongs_to :company
  belongs_to :job_location
end

app/models/job_post_activity.rb
class JobPostActivity < ApplicationRecord
  belongs_to :user_account
  belongs_to :job_post
end

app/models/job_type.rb
class JobType < ApplicationRecord
end

app/models/seeker_profile.rb
class SeekerProfile < ApplicationRecord
end

app/models/seeker_skill_set.rb
class SeekerSkillSet < ApplicationRecord
  belongs_to :user_account
  belongs_to :skill_set
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :user_type
end

app/models/user_log.rb
class UserLog < ApplicationRecord
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/education_details_controller.rb
class EducationDetailsController < ApplicationController
  before_action :set_education_detail, only: [:show, :edit, :update, :destroy]

  # GET /education_details
  # GET /education_details.json
  def index
    @education_details = EducationDetail.all
  end

  # GET /education_details/1
  # GET /education_details/1.json
  def show
  end

  # GET /education_details/new
  def new
    @education_detail = EducationDetail.new
  end

  # GET /education_details/1/edit
  def edit
  end

  # POST /education_details
  # POST /education_details.json
  def create
    @education_detail = EducationDetail.new(education_detail_params)

    respond_to do |format|
      if @education_detail.save
        format.html { redirect_to @education_detail, notice: 'Education detail was successfully created.' }
        format.json { render :show, status: :created, location: @education_detail }
      else
        format.html { render :new }
        format.json { render json: @education_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_details/1
  # PATCH/PUT /education_details/1.json
  def update
    respond_to do |format|
      if @education_detail.update(education_detail_params)
        format.html { redirect_to @education_detail, notice: 'Education detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @education_detail }
      else
        format.html { render :edit }
        format.json { render json: @education_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_details/1
  # DELETE /education_details/1.json
  def destroy
    @education_detail.destroy
    respond_to do |format|
      format.html { redirect_to education_details_url, notice: 'Education detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_detail
      @education_detail = EducationDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_detail_params
      params.require(:education_detail).permit(:user_account_id, :certificate_degree_name, :major, :Institute_university_name, :starting_date, :completion_date, :percentage, :cgpa)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/skill_sets_helper.rb
module SkillSetsHelper
end

app/helpers/user_logs_helper.rb
module UserLogsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/education_details/_form.html.erb
<%= form_with(model: education_detail, local: true) do |form| %>
  <% if education_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education_detail.errors.count, "error") %> prohibited this education_detail from being saved:</h2>

      <ul>
      <% education_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_account_id %>
    <%= form.text_field :user_account_id %>
  </div>

  <div class="field">
    <%= form.label :certificate_degree_name %>
    <%= form.text_field :certificate_degree_name %>
  </div>

  <div class="field">
    <%= form.label :major %>
    <%= form.text_field :major %>
  </div>

  <div class="field">
    <%= form.label :Institute_university_name %>
    <%= form.text_field :Institute_university_name %>
  </div>

  <div class="field">
    <%= form.label :starting_date %>
    <%= form.datetime_select :starting_date %>
  </div>

  <div class="field">
    <%= form.label :completion_date %>
    <%= form.datetime_select :completion_date %>
  </div>

  <div class="field">
    <%= form.label :percentage %>
    <%= form.text_field :percentage %>
  </div>

  <div class="field">
    <%= form.label :cgpa %>
    <%= form.text_field :cgpa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/education_details/edit.html.erb
<h1>Editing Education Detail</h1>

<%= render 'form', education_detail: @education_detail %>

<%= link_to 'Show', @education_detail %> |
<%= link_to 'Back', education_details_path %>

app/views/education_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Education Details</h1>

<table>
  <thead>
    <tr>
      <th>User account</th>
      <th>Certificate degree name</th>
      <th>Major</th>
      <th>Institute university name</th>
      <th>Starting date</th>
      <th>Completion date</th>
      <th>Percentage</th>
      <th>Cgpa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_details.each do |education_detail| %>
      <tr>
        <td><%= education_detail.user_account %></td>
        <td><%= education_detail.certificate_degree_name %></td>
        <td><%= education_detail.major %></td>
        <td><%= education_detail.Institute_university_name %></td>
        <td><%= education_detail.starting_date %></td>
        <td><%= education_detail.completion_date %></td>
        <td><%= education_detail.percentage %></td>
        <td><%= education_detail.cgpa %></td>
        <td><%= link_to 'Show', education_detail %></td>
        <td><%= link_to 'Edit', edit_education_detail_path(education_detail) %></td>
        <td><%= link_to 'Destroy', education_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education Detail', new_education_detail_path %>

app/views/education_details/new.html.erb
<h1>New Education Detail</h1>

<%= render 'form', education_detail: @education_detail %>

<%= link_to 'Back', education_details_path %>

app/views/education_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User account:</strong>
  <%= @education_detail.user_account %>
</p>

<p>
  <strong>Certificate degree name:</strong>
  <%= @education_detail.certificate_degree_name %>
</p>

<p>
  <strong>Major:</strong>
  <%= @education_detail.major %>
</p>

<p>
  <strong>Institute university name:</strong>
  <%= @education_detail.Institute_university_name %>
</p>

<p>
  <strong>Starting date:</strong>
  <%= @education_detail.starting_date %>
</p>

<p>
  <strong>Completion date:</strong>
  <%= @education_detail.completion_date %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @education_detail.percentage %>
</p>

<p>
  <strong>Cgpa:</strong>
  <%= @education_detail.cgpa %>
</p>

<%= link_to 'Edit', edit_education_detail_path(@education_detail) %> |
<%= link_to 'Back', education_details_path %>