config/routes.rb
Rails.application.routes.draw do
  resources :user_types
  resources :user_logs
  resources :user_accounts
  resources :skill_sets
  resources :seeker_skill_sets
  resources :seeker_profiles
  resources :job_types
  resources :job_post_skill_sets
  resources :job_post_activities
  resources :job_posts
  resources :job_locations
  resources :experience_details
  resources :education_details
  resources :company_images
  resources :companies
  resources :business_streams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/business_stream.rb
class BusinessStream < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :business_stream
end

app/models/company_image.rb
class CompanyImage < ApplicationRecord
  belongs_to :company
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/experience_detail.rb
class ExperienceDetail < ApplicationRecord
  belongs_to :user_account
end

app/models/job_location.rb
class JobLocation < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  belongs_to :posted_by
  belongs_to :job_type
  belongs_to :company
  belongs_to :job_location
end

app/models/job_post_activity.rb
class JobPostActivity < ApplicationRecord
  belongs_to :user_account
  belongs_to :job_post
end

app/models/job_type.rb
class JobType < ApplicationRecord
end

app/models/seeker_profile.rb
class SeekerProfile < ApplicationRecord
end

app/models/seeker_skill_set.rb
class SeekerSkillSet < ApplicationRecord
  belongs_to :user_account
  belongs_to :skill_set
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :user_type
end

app/models/user_log.rb
class UserLog < ApplicationRecord
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/company_images_controller.rb
class CompanyImagesController < ApplicationController
  before_action :set_company_image, only: [:show, :edit, :update, :destroy]

  # GET /company_images
  # GET /company_images.json
  def index
    @company_images = CompanyImage.all
  end

  # GET /company_images/1
  # GET /company_images/1.json
  def show
  end

  # GET /company_images/new
  def new
    @company_image = CompanyImage.new
  end

  # GET /company_images/1/edit
  def edit
  end

  # POST /company_images
  # POST /company_images.json
  def create
    @company_image = CompanyImage.new(company_image_params)

    respond_to do |format|
      if @company_image.save
        format.html { redirect_to @company_image, notice: 'Company image was successfully created.' }
        format.json { render :show, status: :created, location: @company_image }
      else
        format.html { render :new }
        format.json { render json: @company_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_images/1
  # PATCH/PUT /company_images/1.json
  def update
    respond_to do |format|
      if @company_image.update(company_image_params)
        format.html { redirect_to @company_image, notice: 'Company image was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_image }
      else
        format.html { render :edit }
        format.json { render json: @company_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_images/1
  # DELETE /company_images/1.json
  def destroy
    @company_image.destroy
    respond_to do |format|
      format.html { redirect_to company_images_url, notice: 'Company image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_image
      @company_image = CompanyImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_image_params
      params.require(:company_image).permit(:company_id, :company_image)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_images_helper.rb
module CompanyImagesHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/skill_sets_helper.rb
module SkillSetsHelper
end

app/helpers/user_logs_helper.rb
module UserLogsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/company_images/_form.html.erb
<%= form_with(model: company_image, local: true) do |form| %>
  <% if company_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_image.errors.count, "error") %> prohibited this company_image from being saved:</h2>

      <ul>
      <% company_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :company_image %>
    <%= form.text_field :company_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/company_images/edit.html.erb
<h1>Editing Company Image</h1>

<%= render 'form', company_image: @company_image %>

<%= link_to 'Show', @company_image %> |
<%= link_to 'Back', company_images_path %>

app/views/company_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Images</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Company image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_images.each do |company_image| %>
      <tr>
        <td><%= company_image.company %></td>
        <td><%= company_image.company_image %></td>
        <td><%= link_to 'Show', company_image %></td>
        <td><%= link_to 'Edit', edit_company_image_path(company_image) %></td>
        <td><%= link_to 'Destroy', company_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Image', new_company_image_path %>

app/views/company_images/new.html.erb
<h1>New Company Image</h1>

<%= render 'form', company_image: @company_image %>

<%= link_to 'Back', company_images_path %>

app/views/company_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @company_image.company %>
</p>

<p>
  <strong>Company image:</strong>
  <%= @company_image.company_image %>
</p>

<%= link_to 'Edit', edit_company_image_path(@company_image) %> |
<%= link_to 'Back', company_images_path %>